# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wesley's Project Site
email: wesleyhitson106@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wesley's project site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: I don't have a twitter
github_username:  wesleyhitson

# Build settings
markdown: kramdown
